//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EValueApi.EValueInstitutionApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Institution_1_0.cfcSoapBinding", Namespace="http://DefaultNamespace")]
    public partial class Institution_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserSubUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubUnitUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Institution_1_0Service() {
            this.Url = global::EValueApi.Properties.Settings.Default.EValueApi_EValueInstitutionApi_Institution_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getUnitsCompletedEventHandler getUnitsCompleted;
        
        /// <remarks/>
        public event getSubUnitsCompletedEventHandler getSubUnitsCompleted;
        
        /// <remarks/>
        public event getUserSubUnitsCompletedEventHandler getUserSubUnitsCompleted;
        
        /// <remarks/>
        public event getSubUnitUsersCompletedEventHandler getSubUnitUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUnitsReturn")]
        public string getUnits(string msg) {
            object[] results = this.Invoke("getUnits", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUnitsAsync(string msg) {
            this.getUnitsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getUnitsAsync(string msg, object userState) {
            if ((this.getUnitsOperationCompleted == null)) {
                this.getUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnitsOperationCompleted);
            }
            this.InvokeAsync("getUnits", new object[] {
                        msg}, this.getUnitsOperationCompleted, userState);
        }
        
        private void OngetUnitsOperationCompleted(object arg) {
            if ((this.getUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUnitsCompleted(this, new getUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSubUnitsReturn")]
        public string getSubUnits(string msg) {
            object[] results = this.Invoke("getSubUnits", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSubUnitsAsync(string msg) {
            this.getSubUnitsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getSubUnitsAsync(string msg, object userState) {
            if ((this.getSubUnitsOperationCompleted == null)) {
                this.getSubUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubUnitsOperationCompleted);
            }
            this.InvokeAsync("getSubUnits", new object[] {
                        msg}, this.getSubUnitsOperationCompleted, userState);
        }
        
        private void OngetSubUnitsOperationCompleted(object arg) {
            if ((this.getSubUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubUnitsCompleted(this, new getSubUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUserSubUnitsReturn")]
        public string getUserSubUnits(string msg) {
            object[] results = this.Invoke("getUserSubUnits", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserSubUnitsAsync(string msg) {
            this.getUserSubUnitsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getUserSubUnitsAsync(string msg, object userState) {
            if ((this.getUserSubUnitsOperationCompleted == null)) {
                this.getUserSubUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserSubUnitsOperationCompleted);
            }
            this.InvokeAsync("getUserSubUnits", new object[] {
                        msg}, this.getUserSubUnitsOperationCompleted, userState);
        }
        
        private void OngetUserSubUnitsOperationCompleted(object arg) {
            if ((this.getUserSubUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserSubUnitsCompleted(this, new getUserSubUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSubUnitUsersReturn")]
        public string getSubUnitUsers(string msg) {
            object[] results = this.Invoke("getSubUnitUsers", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSubUnitUsersAsync(string msg) {
            this.getSubUnitUsersAsync(msg, null);
        }
        
        /// <remarks/>
        public void getSubUnitUsersAsync(string msg, object userState) {
            if ((this.getSubUnitUsersOperationCompleted == null)) {
                this.getSubUnitUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubUnitUsersOperationCompleted);
            }
            this.InvokeAsync("getSubUnitUsers", new object[] {
                        msg}, this.getSubUnitUsersOperationCompleted, userState);
        }
        
        private void OngetSubUnitUsersOperationCompleted(object arg) {
            if ((this.getSubUnitUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubUnitUsersCompleted(this, new getSubUnitUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getUnitsCompletedEventHandler(object sender, getUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getSubUnitsCompletedEventHandler(object sender, getSubUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getUserSubUnitsCompletedEventHandler(object sender, getUserSubUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserSubUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserSubUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getSubUnitUsersCompletedEventHandler(object sender, getSubUnitUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubUnitUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubUnitUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591