//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EValueApi.EValueUserApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="User_1_0.cfcSoapBinding", Namespace="http://DefaultNamespace")]
    public partial class User_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getExtIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPasswdOperationCompleted;
        
        private System.Threading.SendOrPostCallback grantRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByExtIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback revokeGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback addExternalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback revokeRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getByLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback assignGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback rmvExternalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback setLoginIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public User_1_0Service() {
            this.Url = global::EValueApi.Properties.Settings.Default.EValueApi_EValueUserApi_User_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCompletedEventHandler getCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event getRolesCompletedEventHandler getRolesCompleted;
        
        /// <remarks/>
        public event getGroupsCompletedEventHandler getGroupsCompleted;
        
        /// <remarks/>
        public event setStatusCompletedEventHandler setStatusCompleted;
        
        /// <remarks/>
        public event getExtIdsCompletedEventHandler getExtIdsCompleted;
        
        /// <remarks/>
        public event setPasswdCompletedEventHandler setPasswdCompleted;
        
        /// <remarks/>
        public event grantRolesCompletedEventHandler grantRolesCompleted;
        
        /// <remarks/>
        public event getByExtIdCompletedEventHandler getByExtIdCompleted;
        
        /// <remarks/>
        public event revokeGroupsCompletedEventHandler revokeGroupsCompleted;
        
        /// <remarks/>
        public event getByStatusCompletedEventHandler getByStatusCompleted;
        
        /// <remarks/>
        public event addExternalIdCompletedEventHandler addExternalIdCompleted;
        
        /// <remarks/>
        public event revokeRolesCompletedEventHandler revokeRolesCompleted;
        
        /// <remarks/>
        public event getByLoginCompletedEventHandler getByLoginCompleted;
        
        /// <remarks/>
        public event getStatusOptionsCompletedEventHandler getStatusOptionsCompleted;
        
        /// <remarks/>
        public event assignGroupsCompletedEventHandler assignGroupsCompleted;
        
        /// <remarks/>
        public event rmvExternalIdCompletedEventHandler rmvExternalIdCompleted;
        
        /// <remarks/>
        public event setLoginIdCompletedEventHandler setLoginIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReturn")]
        public string get(string msg) {
            object[] results = this.Invoke("get", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAsync(string msg) {
            this.getAsync(msg, null);
        }
        
        /// <remarks/>
        public void getAsync(string msg, object userState) {
            if ((this.getOperationCompleted == null)) {
                this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
            }
            this.InvokeAsync("get", new object[] {
                        msg}, this.getOperationCompleted, userState);
        }
        
        private void OngetOperationCompleted(object arg) {
            if ((this.getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateReturn")]
        public string update(string msg) {
            object[] results = this.Invoke("update", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(string msg) {
            this.updateAsync(msg, null);
        }
        
        /// <remarks/>
        public void updateAsync(string msg, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        msg}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createReturn")]
        public string create(string msg) {
            object[] results = this.Invoke("create", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(string msg) {
            this.createAsync(msg, null);
        }
        
        /// <remarks/>
        public void createAsync(string msg, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        msg}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRolesReturn")]
        public string getRoles(string msg) {
            object[] results = this.Invoke("getRoles", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getRolesAsync(string msg) {
            this.getRolesAsync(msg, null);
        }
        
        /// <remarks/>
        public void getRolesAsync(string msg, object userState) {
            if ((this.getRolesOperationCompleted == null)) {
                this.getRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRolesOperationCompleted);
            }
            this.InvokeAsync("getRoles", new object[] {
                        msg}, this.getRolesOperationCompleted, userState);
        }
        
        private void OngetRolesOperationCompleted(object arg) {
            if ((this.getRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRolesCompleted(this, new getRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getGroupsReturn")]
        public string getGroups(string msg) {
            object[] results = this.Invoke("getGroups", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGroupsAsync(string msg) {
            this.getGroupsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getGroupsAsync(string msg, object userState) {
            if ((this.getGroupsOperationCompleted == null)) {
                this.getGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupsOperationCompleted);
            }
            this.InvokeAsync("getGroups", new object[] {
                        msg}, this.getGroupsOperationCompleted, userState);
        }
        
        private void OngetGroupsOperationCompleted(object arg) {
            if ((this.getGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupsCompleted(this, new getGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("setStatusReturn")]
        public string setStatus(string msg) {
            object[] results = this.Invoke("setStatus", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setStatusAsync(string msg) {
            this.setStatusAsync(msg, null);
        }
        
        /// <remarks/>
        public void setStatusAsync(string msg, object userState) {
            if ((this.setStatusOperationCompleted == null)) {
                this.setStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStatusOperationCompleted);
            }
            this.InvokeAsync("setStatus", new object[] {
                        msg}, this.setStatusOperationCompleted, userState);
        }
        
        private void OnsetStatusOperationCompleted(object arg) {
            if ((this.setStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStatusCompleted(this, new setStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getExtIdsReturn")]
        public string getExtIds(string msg) {
            object[] results = this.Invoke("getExtIds", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getExtIdsAsync(string msg) {
            this.getExtIdsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getExtIdsAsync(string msg, object userState) {
            if ((this.getExtIdsOperationCompleted == null)) {
                this.getExtIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExtIdsOperationCompleted);
            }
            this.InvokeAsync("getExtIds", new object[] {
                        msg}, this.getExtIdsOperationCompleted, userState);
        }
        
        private void OngetExtIdsOperationCompleted(object arg) {
            if ((this.getExtIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExtIdsCompleted(this, new getExtIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("setPasswdReturn")]
        public string setPasswd(string msg) {
            object[] results = this.Invoke("setPasswd", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setPasswdAsync(string msg) {
            this.setPasswdAsync(msg, null);
        }
        
        /// <remarks/>
        public void setPasswdAsync(string msg, object userState) {
            if ((this.setPasswdOperationCompleted == null)) {
                this.setPasswdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPasswdOperationCompleted);
            }
            this.InvokeAsync("setPasswd", new object[] {
                        msg}, this.setPasswdOperationCompleted, userState);
        }
        
        private void OnsetPasswdOperationCompleted(object arg) {
            if ((this.setPasswdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPasswdCompleted(this, new setPasswdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("grantRolesReturn")]
        public string grantRoles(string msg) {
            object[] results = this.Invoke("grantRoles", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void grantRolesAsync(string msg) {
            this.grantRolesAsync(msg, null);
        }
        
        /// <remarks/>
        public void grantRolesAsync(string msg, object userState) {
            if ((this.grantRolesOperationCompleted == null)) {
                this.grantRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngrantRolesOperationCompleted);
            }
            this.InvokeAsync("grantRoles", new object[] {
                        msg}, this.grantRolesOperationCompleted, userState);
        }
        
        private void OngrantRolesOperationCompleted(object arg) {
            if ((this.grantRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grantRolesCompleted(this, new grantRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getByExtIdReturn")]
        public string getByExtId(string msg) {
            object[] results = this.Invoke("getByExtId", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getByExtIdAsync(string msg) {
            this.getByExtIdAsync(msg, null);
        }
        
        /// <remarks/>
        public void getByExtIdAsync(string msg, object userState) {
            if ((this.getByExtIdOperationCompleted == null)) {
                this.getByExtIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByExtIdOperationCompleted);
            }
            this.InvokeAsync("getByExtId", new object[] {
                        msg}, this.getByExtIdOperationCompleted, userState);
        }
        
        private void OngetByExtIdOperationCompleted(object arg) {
            if ((this.getByExtIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByExtIdCompleted(this, new getByExtIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("revokeGroupsReturn")]
        public string revokeGroups(string msg) {
            object[] results = this.Invoke("revokeGroups", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void revokeGroupsAsync(string msg) {
            this.revokeGroupsAsync(msg, null);
        }
        
        /// <remarks/>
        public void revokeGroupsAsync(string msg, object userState) {
            if ((this.revokeGroupsOperationCompleted == null)) {
                this.revokeGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrevokeGroupsOperationCompleted);
            }
            this.InvokeAsync("revokeGroups", new object[] {
                        msg}, this.revokeGroupsOperationCompleted, userState);
        }
        
        private void OnrevokeGroupsOperationCompleted(object arg) {
            if ((this.revokeGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.revokeGroupsCompleted(this, new revokeGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getByStatusReturn")]
        public string getByStatus(string msg) {
            object[] results = this.Invoke("getByStatus", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getByStatusAsync(string msg) {
            this.getByStatusAsync(msg, null);
        }
        
        /// <remarks/>
        public void getByStatusAsync(string msg, object userState) {
            if ((this.getByStatusOperationCompleted == null)) {
                this.getByStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByStatusOperationCompleted);
            }
            this.InvokeAsync("getByStatus", new object[] {
                        msg}, this.getByStatusOperationCompleted, userState);
        }
        
        private void OngetByStatusOperationCompleted(object arg) {
            if ((this.getByStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByStatusCompleted(this, new getByStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("addExternalIdReturn")]
        public string addExternalId(string msg) {
            object[] results = this.Invoke("addExternalId", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addExternalIdAsync(string msg) {
            this.addExternalIdAsync(msg, null);
        }
        
        /// <remarks/>
        public void addExternalIdAsync(string msg, object userState) {
            if ((this.addExternalIdOperationCompleted == null)) {
                this.addExternalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddExternalIdOperationCompleted);
            }
            this.InvokeAsync("addExternalId", new object[] {
                        msg}, this.addExternalIdOperationCompleted, userState);
        }
        
        private void OnaddExternalIdOperationCompleted(object arg) {
            if ((this.addExternalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addExternalIdCompleted(this, new addExternalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("revokeRolesReturn")]
        public string revokeRoles(string msg) {
            object[] results = this.Invoke("revokeRoles", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void revokeRolesAsync(string msg) {
            this.revokeRolesAsync(msg, null);
        }
        
        /// <remarks/>
        public void revokeRolesAsync(string msg, object userState) {
            if ((this.revokeRolesOperationCompleted == null)) {
                this.revokeRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrevokeRolesOperationCompleted);
            }
            this.InvokeAsync("revokeRoles", new object[] {
                        msg}, this.revokeRolesOperationCompleted, userState);
        }
        
        private void OnrevokeRolesOperationCompleted(object arg) {
            if ((this.revokeRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.revokeRolesCompleted(this, new revokeRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getByLoginReturn")]
        public string getByLogin(string msg) {
            object[] results = this.Invoke("getByLogin", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getByLoginAsync(string msg) {
            this.getByLoginAsync(msg, null);
        }
        
        /// <remarks/>
        public void getByLoginAsync(string msg, object userState) {
            if ((this.getByLoginOperationCompleted == null)) {
                this.getByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetByLoginOperationCompleted);
            }
            this.InvokeAsync("getByLogin", new object[] {
                        msg}, this.getByLoginOperationCompleted, userState);
        }
        
        private void OngetByLoginOperationCompleted(object arg) {
            if ((this.getByLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getByLoginCompleted(this, new getByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getStatusOptionsReturn")]
        public string getStatusOptions(string msg) {
            object[] results = this.Invoke("getStatusOptions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusOptionsAsync(string msg) {
            this.getStatusOptionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getStatusOptionsAsync(string msg, object userState) {
            if ((this.getStatusOptionsOperationCompleted == null)) {
                this.getStatusOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOptionsOperationCompleted);
            }
            this.InvokeAsync("getStatusOptions", new object[] {
                        msg}, this.getStatusOptionsOperationCompleted, userState);
        }
        
        private void OngetStatusOptionsOperationCompleted(object arg) {
            if ((this.getStatusOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusOptionsCompleted(this, new getStatusOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("assignGroupsReturn")]
        public string assignGroups(string msg) {
            object[] results = this.Invoke("assignGroups", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void assignGroupsAsync(string msg) {
            this.assignGroupsAsync(msg, null);
        }
        
        /// <remarks/>
        public void assignGroupsAsync(string msg, object userState) {
            if ((this.assignGroupsOperationCompleted == null)) {
                this.assignGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnassignGroupsOperationCompleted);
            }
            this.InvokeAsync("assignGroups", new object[] {
                        msg}, this.assignGroupsOperationCompleted, userState);
        }
        
        private void OnassignGroupsOperationCompleted(object arg) {
            if ((this.assignGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.assignGroupsCompleted(this, new assignGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("rmvExternalIdReturn")]
        public string rmvExternalId(string msg) {
            object[] results = this.Invoke("rmvExternalId", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rmvExternalIdAsync(string msg) {
            this.rmvExternalIdAsync(msg, null);
        }
        
        /// <remarks/>
        public void rmvExternalIdAsync(string msg, object userState) {
            if ((this.rmvExternalIdOperationCompleted == null)) {
                this.rmvExternalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrmvExternalIdOperationCompleted);
            }
            this.InvokeAsync("rmvExternalId", new object[] {
                        msg}, this.rmvExternalIdOperationCompleted, userState);
        }
        
        private void OnrmvExternalIdOperationCompleted(object arg) {
            if ((this.rmvExternalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rmvExternalIdCompleted(this, new rmvExternalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("setLoginIdReturn")]
        public string setLoginId(string msg) {
            object[] results = this.Invoke("setLoginId", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setLoginIdAsync(string msg) {
            this.setLoginIdAsync(msg, null);
        }
        
        /// <remarks/>
        public void setLoginIdAsync(string msg, object userState) {
            if ((this.setLoginIdOperationCompleted == null)) {
                this.setLoginIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetLoginIdOperationCompleted);
            }
            this.InvokeAsync("setLoginId", new object[] {
                        msg}, this.setLoginIdOperationCompleted, userState);
        }
        
        private void OnsetLoginIdOperationCompleted(object arg) {
            if ((this.setLoginIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setLoginIdCompleted(this, new setLoginIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getRolesCompletedEventHandler(object sender, getRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getGroupsCompletedEventHandler(object sender, getGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void setStatusCompletedEventHandler(object sender, setStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getExtIdsCompletedEventHandler(object sender, getExtIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExtIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExtIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void setPasswdCompletedEventHandler(object sender, setPasswdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPasswdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPasswdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void grantRolesCompletedEventHandler(object sender, grantRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class grantRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal grantRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getByExtIdCompletedEventHandler(object sender, getByExtIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByExtIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByExtIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void revokeGroupsCompletedEventHandler(object sender, revokeGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class revokeGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal revokeGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getByStatusCompletedEventHandler(object sender, getByStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void addExternalIdCompletedEventHandler(object sender, addExternalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addExternalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addExternalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void revokeRolesCompletedEventHandler(object sender, revokeRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class revokeRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal revokeRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getByLoginCompletedEventHandler(object sender, getByLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getStatusOptionsCompletedEventHandler(object sender, getStatusOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void assignGroupsCompletedEventHandler(object sender, assignGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class assignGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal assignGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void rmvExternalIdCompletedEventHandler(object sender, rmvExternalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rmvExternalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rmvExternalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void setLoginIdCompletedEventHandler(object sender, setLoginIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setLoginIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setLoginIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591