//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EValueApi.EValuePersonalRecordsApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IandC_1_0.cfcSoapBinding", Namespace="http://DefaultNamespace")]
    public partial class IandC_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback rmvTypeFromSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback linkTypeToSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTemplatePermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSitePermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback linkUserToTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSiteNotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback linkTypeToTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTemplateNotificationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback rmvSitePermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback rmvUserFromTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback rmvTemplatePermissionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IandC_1_0Service() {
            this.Url = global::EValueApi.Properties.Settings.Default.EValueApi_EValuePersonalRecordsApi_IandC_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event getUserDataCompletedEventHandler getUserDataCompleted;
        
        /// <remarks/>
        public event rmvTypeFromSiteCompletedEventHandler rmvTypeFromSiteCompleted;
        
        /// <remarks/>
        public event linkTypeToSiteCompletedEventHandler linkTypeToSiteCompleted;
        
        /// <remarks/>
        public event createTemplateCompletedEventHandler createTemplateCompleted;
        
        /// <remarks/>
        public event createTemplatePermissionsCompletedEventHandler createTemplatePermissionsCompleted;
        
        /// <remarks/>
        public event createSitePermissionsCompletedEventHandler createSitePermissionsCompleted;
        
        /// <remarks/>
        public event linkUserToTemplateCompletedEventHandler linkUserToTemplateCompleted;
        
        /// <remarks/>
        public event createSiteNotificationsCompletedEventHandler createSiteNotificationsCompleted;
        
        /// <remarks/>
        public event linkTypeToTemplateCompletedEventHandler linkTypeToTemplateCompleted;
        
        /// <remarks/>
        public event createTemplateNotificationsCompletedEventHandler createTemplateNotificationsCompleted;
        
        /// <remarks/>
        public event rmvSitePermissionsCompletedEventHandler rmvSitePermissionsCompleted;
        
        /// <remarks/>
        public event rmvUserFromTemplateCompletedEventHandler rmvUserFromTemplateCompleted;
        
        /// <remarks/>
        public event rmvTemplatePermissionsCompletedEventHandler rmvTemplatePermissionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateReturn")]
        public string update(string msg) {
            object[] results = this.Invoke("update", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(string msg) {
            this.updateAsync(msg, null);
        }
        
        /// <remarks/>
        public void updateAsync(string msg, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        msg}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("deleteReturn")]
        public string delete(string msg) {
            object[] results = this.Invoke("delete", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string msg) {
            this.deleteAsync(msg, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string msg, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        msg}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createReturn")]
        public string create(string msg) {
            object[] results = this.Invoke("create", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(string msg) {
            this.createAsync(msg, null);
        }
        
        /// <remarks/>
        public void createAsync(string msg, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        msg}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUserDataReturn")]
        public string getUserData(string msg) {
            object[] results = this.Invoke("getUserData", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserDataAsync(string msg) {
            this.getUserDataAsync(msg, null);
        }
        
        /// <remarks/>
        public void getUserDataAsync(string msg, object userState) {
            if ((this.getUserDataOperationCompleted == null)) {
                this.getUserDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserDataOperationCompleted);
            }
            this.InvokeAsync("getUserData", new object[] {
                        msg}, this.getUserDataOperationCompleted, userState);
        }
        
        private void OngetUserDataOperationCompleted(object arg) {
            if ((this.getUserDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserDataCompleted(this, new getUserDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("rmvTypeFromSiteReturn")]
        public string rmvTypeFromSite(string msg) {
            object[] results = this.Invoke("rmvTypeFromSite", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rmvTypeFromSiteAsync(string msg) {
            this.rmvTypeFromSiteAsync(msg, null);
        }
        
        /// <remarks/>
        public void rmvTypeFromSiteAsync(string msg, object userState) {
            if ((this.rmvTypeFromSiteOperationCompleted == null)) {
                this.rmvTypeFromSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrmvTypeFromSiteOperationCompleted);
            }
            this.InvokeAsync("rmvTypeFromSite", new object[] {
                        msg}, this.rmvTypeFromSiteOperationCompleted, userState);
        }
        
        private void OnrmvTypeFromSiteOperationCompleted(object arg) {
            if ((this.rmvTypeFromSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rmvTypeFromSiteCompleted(this, new rmvTypeFromSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("linkTypeToSiteReturn")]
        public string linkTypeToSite(string msg) {
            object[] results = this.Invoke("linkTypeToSite", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void linkTypeToSiteAsync(string msg) {
            this.linkTypeToSiteAsync(msg, null);
        }
        
        /// <remarks/>
        public void linkTypeToSiteAsync(string msg, object userState) {
            if ((this.linkTypeToSiteOperationCompleted == null)) {
                this.linkTypeToSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlinkTypeToSiteOperationCompleted);
            }
            this.InvokeAsync("linkTypeToSite", new object[] {
                        msg}, this.linkTypeToSiteOperationCompleted, userState);
        }
        
        private void OnlinkTypeToSiteOperationCompleted(object arg) {
            if ((this.linkTypeToSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.linkTypeToSiteCompleted(this, new linkTypeToSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createTemplateReturn")]
        public string createTemplate(string msg) {
            object[] results = this.Invoke("createTemplate", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createTemplateAsync(string msg) {
            this.createTemplateAsync(msg, null);
        }
        
        /// <remarks/>
        public void createTemplateAsync(string msg, object userState) {
            if ((this.createTemplateOperationCompleted == null)) {
                this.createTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTemplateOperationCompleted);
            }
            this.InvokeAsync("createTemplate", new object[] {
                        msg}, this.createTemplateOperationCompleted, userState);
        }
        
        private void OncreateTemplateOperationCompleted(object arg) {
            if ((this.createTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTemplateCompleted(this, new createTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createTemplatePermissionsReturn")]
        public string createTemplatePermissions(string msg) {
            object[] results = this.Invoke("createTemplatePermissions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createTemplatePermissionsAsync(string msg) {
            this.createTemplatePermissionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void createTemplatePermissionsAsync(string msg, object userState) {
            if ((this.createTemplatePermissionsOperationCompleted == null)) {
                this.createTemplatePermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTemplatePermissionsOperationCompleted);
            }
            this.InvokeAsync("createTemplatePermissions", new object[] {
                        msg}, this.createTemplatePermissionsOperationCompleted, userState);
        }
        
        private void OncreateTemplatePermissionsOperationCompleted(object arg) {
            if ((this.createTemplatePermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTemplatePermissionsCompleted(this, new createTemplatePermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createSitePermissionsReturn")]
        public string createSitePermissions(string msg) {
            object[] results = this.Invoke("createSitePermissions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSitePermissionsAsync(string msg) {
            this.createSitePermissionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void createSitePermissionsAsync(string msg, object userState) {
            if ((this.createSitePermissionsOperationCompleted == null)) {
                this.createSitePermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSitePermissionsOperationCompleted);
            }
            this.InvokeAsync("createSitePermissions", new object[] {
                        msg}, this.createSitePermissionsOperationCompleted, userState);
        }
        
        private void OncreateSitePermissionsOperationCompleted(object arg) {
            if ((this.createSitePermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSitePermissionsCompleted(this, new createSitePermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("linkUserToTemplateReturn")]
        public string linkUserToTemplate(string msg) {
            object[] results = this.Invoke("linkUserToTemplate", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void linkUserToTemplateAsync(string msg) {
            this.linkUserToTemplateAsync(msg, null);
        }
        
        /// <remarks/>
        public void linkUserToTemplateAsync(string msg, object userState) {
            if ((this.linkUserToTemplateOperationCompleted == null)) {
                this.linkUserToTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlinkUserToTemplateOperationCompleted);
            }
            this.InvokeAsync("linkUserToTemplate", new object[] {
                        msg}, this.linkUserToTemplateOperationCompleted, userState);
        }
        
        private void OnlinkUserToTemplateOperationCompleted(object arg) {
            if ((this.linkUserToTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.linkUserToTemplateCompleted(this, new linkUserToTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createSiteNotificationsReturn")]
        public string createSiteNotifications(string msg) {
            object[] results = this.Invoke("createSiteNotifications", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSiteNotificationsAsync(string msg) {
            this.createSiteNotificationsAsync(msg, null);
        }
        
        /// <remarks/>
        public void createSiteNotificationsAsync(string msg, object userState) {
            if ((this.createSiteNotificationsOperationCompleted == null)) {
                this.createSiteNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSiteNotificationsOperationCompleted);
            }
            this.InvokeAsync("createSiteNotifications", new object[] {
                        msg}, this.createSiteNotificationsOperationCompleted, userState);
        }
        
        private void OncreateSiteNotificationsOperationCompleted(object arg) {
            if ((this.createSiteNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSiteNotificationsCompleted(this, new createSiteNotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("linkTypeToTemplateReturn")]
        public string linkTypeToTemplate(string msg) {
            object[] results = this.Invoke("linkTypeToTemplate", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void linkTypeToTemplateAsync(string msg) {
            this.linkTypeToTemplateAsync(msg, null);
        }
        
        /// <remarks/>
        public void linkTypeToTemplateAsync(string msg, object userState) {
            if ((this.linkTypeToTemplateOperationCompleted == null)) {
                this.linkTypeToTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlinkTypeToTemplateOperationCompleted);
            }
            this.InvokeAsync("linkTypeToTemplate", new object[] {
                        msg}, this.linkTypeToTemplateOperationCompleted, userState);
        }
        
        private void OnlinkTypeToTemplateOperationCompleted(object arg) {
            if ((this.linkTypeToTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.linkTypeToTemplateCompleted(this, new linkTypeToTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("createTemplateNotificationsReturn")]
        public string createTemplateNotifications(string msg) {
            object[] results = this.Invoke("createTemplateNotifications", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createTemplateNotificationsAsync(string msg) {
            this.createTemplateNotificationsAsync(msg, null);
        }
        
        /// <remarks/>
        public void createTemplateNotificationsAsync(string msg, object userState) {
            if ((this.createTemplateNotificationsOperationCompleted == null)) {
                this.createTemplateNotificationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTemplateNotificationsOperationCompleted);
            }
            this.InvokeAsync("createTemplateNotifications", new object[] {
                        msg}, this.createTemplateNotificationsOperationCompleted, userState);
        }
        
        private void OncreateTemplateNotificationsOperationCompleted(object arg) {
            if ((this.createTemplateNotificationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTemplateNotificationsCompleted(this, new createTemplateNotificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("rmvSitePermissionsReturn")]
        public string rmvSitePermissions(string msg) {
            object[] results = this.Invoke("rmvSitePermissions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rmvSitePermissionsAsync(string msg) {
            this.rmvSitePermissionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void rmvSitePermissionsAsync(string msg, object userState) {
            if ((this.rmvSitePermissionsOperationCompleted == null)) {
                this.rmvSitePermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrmvSitePermissionsOperationCompleted);
            }
            this.InvokeAsync("rmvSitePermissions", new object[] {
                        msg}, this.rmvSitePermissionsOperationCompleted, userState);
        }
        
        private void OnrmvSitePermissionsOperationCompleted(object arg) {
            if ((this.rmvSitePermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rmvSitePermissionsCompleted(this, new rmvSitePermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("rmvUserFromTemplateReturn")]
        public string rmvUserFromTemplate(string msg) {
            object[] results = this.Invoke("rmvUserFromTemplate", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rmvUserFromTemplateAsync(string msg) {
            this.rmvUserFromTemplateAsync(msg, null);
        }
        
        /// <remarks/>
        public void rmvUserFromTemplateAsync(string msg, object userState) {
            if ((this.rmvUserFromTemplateOperationCompleted == null)) {
                this.rmvUserFromTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrmvUserFromTemplateOperationCompleted);
            }
            this.InvokeAsync("rmvUserFromTemplate", new object[] {
                        msg}, this.rmvUserFromTemplateOperationCompleted, userState);
        }
        
        private void OnrmvUserFromTemplateOperationCompleted(object arg) {
            if ((this.rmvUserFromTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rmvUserFromTemplateCompleted(this, new rmvUserFromTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("rmvTemplatePermissionsReturn")]
        public string rmvTemplatePermissions(string msg) {
            object[] results = this.Invoke("rmvTemplatePermissions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rmvTemplatePermissionsAsync(string msg) {
            this.rmvTemplatePermissionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void rmvTemplatePermissionsAsync(string msg, object userState) {
            if ((this.rmvTemplatePermissionsOperationCompleted == null)) {
                this.rmvTemplatePermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrmvTemplatePermissionsOperationCompleted);
            }
            this.InvokeAsync("rmvTemplatePermissions", new object[] {
                        msg}, this.rmvTemplatePermissionsOperationCompleted, userState);
        }
        
        private void OnrmvTemplatePermissionsOperationCompleted(object arg) {
            if ((this.rmvTemplatePermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rmvTemplatePermissionsCompleted(this, new rmvTemplatePermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getUserDataCompletedEventHandler(object sender, getUserDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void rmvTypeFromSiteCompletedEventHandler(object sender, rmvTypeFromSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rmvTypeFromSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rmvTypeFromSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void linkTypeToSiteCompletedEventHandler(object sender, linkTypeToSiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class linkTypeToSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal linkTypeToSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createTemplateCompletedEventHandler(object sender, createTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createTemplatePermissionsCompletedEventHandler(object sender, createTemplatePermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createTemplatePermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createTemplatePermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createSitePermissionsCompletedEventHandler(object sender, createSitePermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSitePermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSitePermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void linkUserToTemplateCompletedEventHandler(object sender, linkUserToTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class linkUserToTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal linkUserToTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createSiteNotificationsCompletedEventHandler(object sender, createSiteNotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSiteNotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSiteNotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void linkTypeToTemplateCompletedEventHandler(object sender, linkTypeToTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class linkTypeToTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal linkTypeToTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void createTemplateNotificationsCompletedEventHandler(object sender, createTemplateNotificationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createTemplateNotificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createTemplateNotificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void rmvSitePermissionsCompletedEventHandler(object sender, rmvSitePermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rmvSitePermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rmvSitePermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void rmvUserFromTemplateCompletedEventHandler(object sender, rmvUserFromTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rmvUserFromTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rmvUserFromTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void rmvTemplatePermissionsCompletedEventHandler(object sender, rmvTemplatePermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rmvTemplatePermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rmvTemplatePermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591