//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EValueApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Institution_1_0.cfc")]
        public string EValueApi_EValueInstitutionApi_Institution_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueInstitutionApi_Institution_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/User_1_0b.cfc")]
        public string EValueApi_EValueUserApi_User_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueUserApi_User_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Site_1_0.cfc")]
        public string EValueApi_EValueSiteApi_Site_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueSiteApi_Site_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/TimeFrame_1_0.cfc")]
        public string EValueApi_EValueTimeFrameApi_TimeFrame_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueTimeFrameApi_TimeFrame_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/IandC_1_0.cfc")]
        public string EValueApi_EValuePersonalRecordsApi_IandC_1_0Service {
            get {
                return ((string)(this["EValueApi_EValuePersonalRecordsApi_IandC_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Activity_1_0b.cfc")]
        public string EValueApi_EValueActivityApi_Activity_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueActivityApi_Activity_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Schedule_1_0b.cfc")]
        public string EValueApi_EValueScheduleApi_Schedule_1_0bService {
            get {
                return ((string)(this["EValueApi_EValueScheduleApi_Schedule_1_0bService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Evaluation_1_0b.cfc")]
        public string EValueApi_EValueEvaluationApi_Evaluation_1_0bService {
            get {
                return ((string)(this["EValueApi_EValueEvaluationApi_Evaluation_1_0bService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Role_1_0.cfc")]
        public string EValueApi_EValueRoleApi_Role_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueRoleApi_Role_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Rank_1_0.cfc")]
        public string EValueApi_EValueRankApi_Rank_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueRankApi_Rank_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Status_1_0.cfc")]
        public string EValueApi_EValueStatusApi_Status_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueStatusApi_Status_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/PeopleGroup_1_0.cfc")]
        public string EValueApi_EValuePeopleGroupApi_PeopleGroup_1_0Service {
            get {
                return ((string)(this["EValueApi_EValuePeopleGroupApi_PeopleGroup_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/IandCOptions_1_0.cfc")]
        public string EValueApi_EValuePersonalRecordsOptionsApi_IandCOptions_1_0Service {
            get {
                return ((string)(this["EValueApi_EValuePersonalRecordsOptionsApi_IandCOptions_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test-api.e-value.net/Team_1_0.cfc")]
        public string EValueApi_EValueTeamApi_Team_1_0Service {
            get {
                return ((string)(this["EValueApi_EValueTeamApi_Team_1_0Service"]));
            }
        }
    }
}
