//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EValueApi.EValuePersonalRecordsOptionsApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IandCOptions_1_0.cfcSoapBinding", Namespace="http://DefaultNamespace")]
    public partial class IandCOptions_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getTypeOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRequirementOptionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IandCOptions_1_0Service() {
            this.Url = global::EValueApi.Properties.Settings.Default.EValueApi_EValuePersonalRecordsOptionsApi_IandCOptions_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getTypeOptionsCompletedEventHandler getTypeOptionsCompleted;
        
        /// <remarks/>
        public event getStatusOptionsCompletedEventHandler getStatusOptionsCompleted;
        
        /// <remarks/>
        public event getRequirementOptionsCompletedEventHandler getRequirementOptionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getTypeOptionsReturn")]
        public string getTypeOptions(string msg) {
            object[] results = this.Invoke("getTypeOptions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTypeOptionsAsync(string msg) {
            this.getTypeOptionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getTypeOptionsAsync(string msg, object userState) {
            if ((this.getTypeOptionsOperationCompleted == null)) {
                this.getTypeOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTypeOptionsOperationCompleted);
            }
            this.InvokeAsync("getTypeOptions", new object[] {
                        msg}, this.getTypeOptionsOperationCompleted, userState);
        }
        
        private void OngetTypeOptionsOperationCompleted(object arg) {
            if ((this.getTypeOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTypeOptionsCompleted(this, new getTypeOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getStatusOptionsReturn")]
        public string getStatusOptions(string msg) {
            object[] results = this.Invoke("getStatusOptions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusOptionsAsync(string msg) {
            this.getStatusOptionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getStatusOptionsAsync(string msg, object userState) {
            if ((this.getStatusOptionsOperationCompleted == null)) {
                this.getStatusOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOptionsOperationCompleted);
            }
            this.InvokeAsync("getStatusOptions", new object[] {
                        msg}, this.getStatusOptionsOperationCompleted, userState);
        }
        
        private void OngetStatusOptionsOperationCompleted(object arg) {
            if ((this.getStatusOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusOptionsCompleted(this, new getStatusOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://DefaultNamespace", ResponseNamespace="http://DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("getRequirementOptionsReturn")]
        public string getRequirementOptions(string msg) {
            object[] results = this.Invoke("getRequirementOptions", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getRequirementOptionsAsync(string msg) {
            this.getRequirementOptionsAsync(msg, null);
        }
        
        /// <remarks/>
        public void getRequirementOptionsAsync(string msg, object userState) {
            if ((this.getRequirementOptionsOperationCompleted == null)) {
                this.getRequirementOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRequirementOptionsOperationCompleted);
            }
            this.InvokeAsync("getRequirementOptions", new object[] {
                        msg}, this.getRequirementOptionsOperationCompleted, userState);
        }
        
        private void OngetRequirementOptionsOperationCompleted(object arg) {
            if ((this.getRequirementOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRequirementOptionsCompleted(this, new getRequirementOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getTypeOptionsCompletedEventHandler(object sender, getTypeOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTypeOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTypeOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getStatusOptionsCompletedEventHandler(object sender, getStatusOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void getRequirementOptionsCompletedEventHandler(object sender, getRequirementOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRequirementOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRequirementOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591